---
- hosts: _sarahlynch
  roles:
    - {role: install-nginx }
    - {role: configtree, CONFIGTREE_PATH: "{{inventory_dir | basename}}/_sarahlynch/" }
    - {role: configtree, CONFIGTREE_PATH: "{{inventory_dir | basename}}/{{ansible_hostname}}/" }
  post_tasks:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes
      become: yes
